### DISCUSSION TITLE
Дополнения к документации

### DISCUSSION THREAD

**Discussion by glebsterx** [dext0r/yandex_smart_home#547] [Ideas]
В чате искать неудобно, надо тут оформить все предложения по добавлению в оф. документацию.
Я начну:
1. Удаление режима реализуется так
```
      modes:
        program: 
          low: [x]
```
2. кейс с двумя ХА (в разных сетях, дом и дача например) и одним акком -- в чате раз в неделю всплывает.
Описать варианты решения
- прямое + облако
- прямое + прямое
- Remote home assistant

3. Новшества в ХА -- действия которые раньше были сервисами -- надо или апдейт полный или примечание сделать

**Comment by glebsterx** [comment]
Коллеги пишут:
Для продвинутых - Пользовательские умения - custom_ranges
во всех примерах даётся вот такой вид конфига, где entity_id стоит в одном ряду с service и data
```
 set_value:
   service: xiaomi_miio_airpurifier.fan_set_favorite_speed
   entity_id: fan.xiaomi_airfresh_a1
   data:
     speed: '{{ value }}'
```
но это не работает. Потом в рецептах посмотрел в конце, и там нужно писать target:

```
 set_value:
   service: xiaomi_miio_airpurifier.fan_set_favorite_speed
   target:
     entity_id: fan.xiaomi_airfresh_a1
   data:
     speed: '{{ value }}'
```
и вот это уже работает.


Я думаю насчет этого -- на самом деле раньше (не помню до какой версии) никакого target не было в вызовах служб(нынче действия или как там они)
ХА постоянное меняется конечно, но для обратной совместимости вроде как работали оба варианта -- возможно для каких-то обновленных интеграций или особых фич нужно писать именно с таргетом...
