### ISSUE TITLE
Новый способ настроить кнопки

### ISSUE THREAD

**Issue by dext0r** [dext0r/yandex_smart_home#395]
На текущий момент нет единого механизма, который позволит единообразно настроить кнопки для передачи в УДЯ. Реализация кнопок в HA - это зоопарк, кнопки бывают:
1. В виде entity, у которой в state появляется `click`, `double_click` и т.п. - автоматически не обнаружить, нет `device_class`. Такая реализация в AlexxIT/XiaomiGateway3
2. Как первая, только в state ничего не появляется, а при клике бросается событие: например `xiaomi_aqara.click` в ядерной интеграции [xiaomi_aqara](https://github.com/home-assistant/core/blob/a0ed54465f25b4c6a4b78495174f8b18128a43d9/homeassistant/components/xiaomi_aqara/binary_sensor.py#L491)
3. Только в виде событий Device Automation - entity нет вообще, а действия могут быть [любыми](https://github.com/Koenkk/zigbee-herdsman-converters/blob/f6cc4031df80f11ab4032b652930ab6d232f4d42/devices/xiaomi.js#L527). Такие кнопки в zigbee2mqtt с выключенным legacy режимом.

Предлагается сделать настройку кнопок через YAML в настройках интеграции (GUI позже):
```yaml
yandex_smart_home:
  button:
    - platform: state  # для кнопок 1
      entity_id: sensor.some_button_action
    
    - platform: event  # для кнопок 2
      entity_id: sensor.xiaomi_button
      event_type: xiaomi_aqara.click

    - platform: device  # z2m через device automation
      device_id: 2842b2316f4f28b5354e8b0de3aad924  # это и следующее поле можно будет взять из конструктора автоматизаций
      type: action
      actions:  # маппинг удя-ха, по дефолту будут смаплены "популярные события", возможен для всех платформ
         click: brightness_move_up
         double_click: 'on'
```
