### ISSUE TITLE
Валидация YAML c двойным entity_config

### ISSUE THREAD

**Issue by dext0r** [dext0r/yandex_smart_home#410]
Такой YAML считается валидным, хотя не должен:
```yaml
yandex_smart_home:
  entity_config:
    cover.room:
      state_unknown: true
  entity_config:
    climate.ac:
      type: devices.types.thermostat.ac
```
