### ISSUE TITLE
Программы увлажнителя

### ISSUE THREAD

**Issue by c7v** [dext0r/yandex_smart_home#416]
В документации есть пример [добавление датчиков в увлажнитель Mi](https://docs.yaha-cloud.ru/v0.6.x/devices/sensor/#attach). Но, я не нашёл в документации как переименовать название программ увлажнителя:

```yaml
yandex_smart_home:
  entity_config:
    humidifier.deerma_jsq5_e61c_humidifier:
      properties:
        - type: temperature
          entity: sensor.deerma_jsq5_e61c_temperature
        - type: humidity
          entity: sensor.deerma_jsq5_e61c_relative_humidity
```

в УДЯ:
![image](https://user-images.githubusercontent.com/50216354/197399507-6844b5e5-e427-4ad9-acab-b5eaba6d6d16.png)

в HA:
![image](https://user-images.githubusercontent.com/50216354/197399567-55437ddb-c649-43a3-89c0-c221e7038957.png)
