### ISSUE TITLE
Данные о температуре и влажности в увлажнителе

### ISSUE THREAD

**Issue by kaizer666** [dext0r/yandex_smart_home#428]
Настроил увлажнитель:

```
humidifier.deerma_jsq_9613_humidifier_2:
      name: Увлажнитель
      properties:
        - type: humidity
          entity: sensor.deerma_jsq_9613_relative_humidity
        - type: temperature
          entity: sensor.deerma_jsq_9613_temperature
      custom_toggles:
        backlight:
          state_entity_id: light.deerma_jsq_9613_indicator_light
          state_attribute: indicator_light.on
          turn_on:
            service: light.turn_on
            entity_id: light.deerma_jsq_9613_indicator_light
          turn_off:
            service: light.turn_off
            entity_id: light.deerma_jsq_9613_indicator_light
        mute:
          state_entity_id: switch.deerma_jsq_9613_alarm
          state_attribute: alarm
          turn_on:
            service: switch.turn_off
            entity_id: switch.deerma_jsq_9613_alarm
          turn_off:
            service: switch.turn_on
            entity_id: switch.deerma_jsq_9613_alarm
      modes:
        program:
          low: ["Low"]
          medium: ["Medium"]
          high: ["High"]
          auto: ["ConstHumidity"]
```

Но данные о температуре и влажности не передаются. В логах УДЯ такие ошибки

`2023-01-25T15:06:25+03:00: State validation for device {id:efba8c0e-7113-4291-80a4-28cd6c9ef7c8, external_id:humidifier.deerma_jsq_9613_humidifier_2, provider:88a08f8b-57b2-4c7e-8bc7-163a471b6955, user:14153243} failed: range humidity instance state value is out of supported range: '0.000000'`

`2023-01-25T15:06:25+03:00: Device {id:efba8c0e-7113-4291-80a4-28cd6c9ef7c8, external_id:humidifier.deerma_jsq_9613_humidifier_2, provider:88a08f8b-57b2-4c7e-8bc7-163a471b6955, user:14153243} not updated: State error: [INVALID_VALUE] `

В логах ХА всё чисто в этот момент. Сенсоры активные, данные на них есть. И меняются.

В логах УДЯ данные приходят верно 

`2023-01-25T15:06:35+03:00: Got response from provider 88a08f8b-57b2-4c7e-8bc7-163a471b6955:
200
{"request_id":"26b216ad-d258-445b-91ed-dcac9ae53d2d","payload":{"devices":[{"id":"humidifier.deerma_jsq_9613_humidifier_2","capabilities":[{"type":"devices.capabilities.toggle","state":{"instance":"backlight","value":true}},{"type":"devices.capabilities.toggle","state":{"instance":"mute","value":true}},{"type":"devices.capabilities.range","state":{"instance":"humidity","value":0.0}},{"type":"devices.capabilities.on_off","state":{"instance":"on","value":false}}],"properties":[{"type":"devices.properties.float","state":{"instance":"humidity","value":29.0}},{"type":"devices.properties.float","state":{"instance":"temperature","value":24.0}}]}]}}`
