### ISSUE TITLE
Возврат любых доступных ошибок при управлении устройством

### ISSUE THREAD

**Issue by dext0r** [dext0r/yandex_smart_home#437]
Сейчас при управлении устройством компонент умеет возвращать ограниченный набор ошибок ("устройство недоступно", "что-то пошло не так", "не поддерживается в текущем режиме"). УДЯ поддерживает куда больше ошибок ([полный список](https://yandex.ru/dev/dialogs/smart-home/doc/concepts/response-codes.html)), которая Алиса может озвучить.

Из интересных:
* Недостаточно воды - мастхев для чайников, привет DIYщикам с HX711 ;)
* Устройство застряло - пылесосы? (кейс придумать не могу, не владею :))
* Удаленное управление устройством отключено - когда пытаешься включить кондиционер в -30 (а это очень плохая идея)

Сам HA никак не умеет возвращать адекватные ошибки при вызове сервисов, поэтому ошибку должен формировать компонент. Предлагается добавить в `entity_config` настройку `error_code_template`, в которой задавать шаблон, возвращающий код ответа. При получении команды на управление устройство этот шаблон будет рендерится (с передачей сырого capability), и если при рендеринге вернулось значение - отдавать его в качестве `error_code` в сторону УДЯ.

Пример как это может выглядеть:
```
yandex_smart_home:
  entity_config:
    climate.kettle:
      error_code_template: |
        {% if capability.type == 'devices.capabilities.on_off' and capability.state.instance == 'on' and capability.state.value %}
          {% if states('sensor.kettle_water_level')|int(0) < 10 %}  # тут 10 - это проценты
            NOT_ENOUGH_WATER
          {% endif %}
        {% endif %}
```

Содержимое `capability` для включения:
```
{
  "type": "devices.capabilities.on_off",
  "state": {
    "instance": "on",
     "value": false
  }
}
```

**Comment by Sergey-SRG** [comment]
Недостаточно воды - не только для чайников но и для увлажнителя тоже крутая штука будет!

**Comment by Sergey-SRG** [comment]
Все отлично работает!

![Screenshot_2023-03-13-01-48-07-559_com.yandex.iot.jpg](https://user-images.githubusercontent.com/3891900/224578643-e7f3ad5a-f08d-4aff-baa9-7384164d3982.jpg)

```
switch.smart_energy_meter_switch:
      name: Электросеть
      properties:
        - type: voltage
          entity: sensor.smart_energy_meter_voltage
        - type: amperage
          entity: sensor.smart_energy_meter_current
        - type: power
          entity: sensor.smart_energy_meter_power
      error_code_template: |
        {% if capability.type == 'devices.capabilities.on_off' and capability.state.instance == 'on' and capability.state.value == false%}
            REMOTE_CONTROL_DISABLED
        {% endif %}
```
