### ISSUE TITLE
Единица измерения для датчика давления воды

### ISSUE THREAD

**Issue by booroondook-eng** [dext0r/yandex_smart_home#448]
Имеется датчик давления жидкости (в системе отопления).
В Home Assistant'е выдает давление в барах - например, 1,35 или 1,52.
Однако в УДЯ давление отображается в мм рт.ст., причем пересчитанное - то есть, если в ХА я в;ду 1,52 бар, то в УДЯ я вижу 1040 мм рт.ст.
Но мне-то надо, чтобы УДЯ показывал давление именно на этом датчике в барах!
Прописал такую конфигурацию:
```
yandex_smart_home:
  entity_config:
    sensor.heating_liquid_pressure:
      name: Система отопления
      properties:
        - type: pressure
          entity: sensor.heating_liquid_pressure
          unit_of_measurement: bar

```
Не помогло - все равно УДЯ показывает мм рт.ст.
Пробовал заменить "bar" на "бар" и даже на "unit.pressure.bar" - не помогает.
В общих настройках интеграции прописано:
```
yandex_smart_home:
  settings:
    pressure_unit: mmHg

```
Подозреваю, что если изменю эту общую настройку, то это повлияет на все датчики, измеряющие **атмосферное** давление. А вот атмосферное давление хотелось бы видеть именно в мм рт.ст.

**Comment by dext0r** [comment]
На данный момент нет поддержки разных единиц измерения для разных датчиков давления. Помечу эта задачу как фичреквест.

**Comment by booroondook-eng** [comment]
Вдогонку. Столкнулся с похожей проблемой, но тут уже речь не о давлении, а о напряжении.
Часть датчиков сообщает напряжение батарейки в вольтах (например, 2.95), а часть - в милливольтах (например, 2952).
В УДЯ для всех датчиков отображаются вольты, причем без конверсии (т.е. например, 2952 вольта!)

**Comment by booroondook-eng** [comment]
> Значит для такого объекта в HA не задан (или задан неверный) атрибут `unit_of_measurement`
> 
Все задано правильно, не нужно обвинять интеграцуию:


![2023-06-07 18_00_58-Window](https://github.com/dext0r/yandex_smart_home/assets/8210458/8f7c3e5f-c824-4d8a-ab6d-2bc5659110ca)

**Comment by dext0r** [comment]
> > Значит для такого объекта в HA не задан (или задан неверный) атрибут `unit_of_measurement`
> 
> Все задано правильно, не нужно обвинять интеграцию:
> 
> ![2023-06-07 18_00_58-Window](https://user-images.githubusercontent.com/8210458/244110279-8f7c3e5f-c824-4d8a-ab6d-2bc5659110ca.png)

Какие нибудь настройки в entity_config для этого сенсора заданы?

**Comment by booroondook-eng** [comment]
```
      sensor.xxxxx_action:
        name: ХХХХХХХХ
        device_class: button
        room: ХХХХХХ
        properties:
          - type: button
            entity: sensor.xxxxx_action
          - type: battery_level
            entity: sensor.xxxxx_battery
          - type: temperature
            entity: sensor.xxxxx_device_temperature
          - type: voltage
            entity: sensor.xxxxx_voltage
            unit_of_measurement: mV

```
