### ISSUE TITLE
Асинхронный запуск команд

### ISSUE THREAD

**Issue by panfmik** [dext0r/yandex_smart_home#475]
Возможно ли добавить поддержку state_unknown для домена switch?
https://docs.yaha-cloud.ru/v0.6.x/config/entity/#state_unknown

Проблема следующая, есть switch у которого долго меняется статус и в ответ на это Алиса говорит что произошла ошибка. По факту команда выполнена, если я не ошибаюсь затык в том что УДЯ ожидает быстрый ответ на изменение статуса, по логике получается если добавить state_unknown то проблема должна решиться.

**Comment by dext0r** [comment]
Начиная с 0.6.1 поддерживается для всех доменов. Но она не влияет на то, как исполняются команды. Нужно чинить на стороне HA, чтобы команда укладывалась в 3 секунды.

**Comment by panfmik** [comment]
так если добавить state_unknown алиса не будет ожидать изменение статуса а просто сделает ВКЛ/ВЫКЛ?

**Comment by dext0r** [comment]
> так если добавить state_unknown алиса не будет ожидать изменение статуса а просто сделает ВКЛ/ВЫКЛ?

Компонент не ожидает смену статуса, он вызывает сервис `switch.turn_on` или `switch.turn_off` и ждёт когда он завершится.

Какой интеграцией предоставлен свитч, с которым у вас возникает проблема?

**Comment by panfmik** [comment]
[starline](https://www.home-assistant.io/integrations/starline)

**Comment by dext0r** [comment]
Посмотрел код компонента и API от старлайна - стало понятно, почему `service.turn_on` долго выполняется. Подумаю, что можно с этим сделать.

В качестве временного костыля можно создать скрипт, в котором будет включаться свитч, а в entity_config внести вызов скрипта в асинхронном режиме:
```yaml
yandex_smart_home:
  entity_config:
    switch.startline_engine:
      turn_on:
        service: script.turn_on  # это запустит скрипт асинхронно
        entity_id: script.startline_engine_on
      turn_off:
        service: script.turn_on
        entity_id: script.startline_engine_off

script:
  startline_engine_on:
    sequence:
      - service: switch.turn_on
        entity_id: switch.startline_engine
  startline_engine_off:
    sequence:
      - service: switch.turn_off
        entity_id: switch.startline_engine

```
