### ISSUE TITLE
Некорректная работа некоторых range умений без поддержки random_access

### ISSUE THREAD

**Issue by dext0r** [dext0r/yandex_smart_home#482]
Для:
```yaml
  entity_config:
    media_player.bedroom:
      custom_ranges:
        brightness:
          increase_value:
            service: notify.debug
            data:
              message: up
          decrease_value:
            service: notify.debug
            data:
              message: down

```

На decrease приходит - `0`, для increase - `1`.
Однако для `channel` приходит для decrease - `-1`, для `increase` - `1`
Проверить все функции (и с set_value тоже - https://t.me/yandex_smart_home/71109)!
