### ISSUE TITLE
Не работает проброс класса washing_machine

### ISSUE THREAD

**Issue by Losenmann** [dext0r/yandex_smart_home#485]
При добавлении в конфигурацию стиральной машины, она не передается УЯД. Ошибок ни каких нет. Стиральная машина добавлена в HA через интеграцию "smartthinq_sensors". Данные в HA от нее приходят. Прикладываю фрагмент конфигурации:
```
filter:
  include_entities:
    - switch.pc_power
    - input_boolean.pc_led
    - media_player.lg_webos_smart_tv
    - media_player.xiaomi_mi_tv_4s
    - sensor.aqara_weather_1_temperature
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_opening_1
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_opening_2
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_opening_3
    - binary_sensor.aqara_magnet_1_opening
    - vacuum.ijai_v17_6ebf_robot_cleaner
    - sensor.stiralnaia_mashina

entity_config:
  sensor.stiralnaia_mashina:
    name: "Стиралка"
    room: "Ванная"
    type: "devices.types.washing_machine"
```

**Comment by dext0r** [comment]
Что именно находится в сенсоре `sensor.stiralnaia_mashina`? Покажите его атрибуты и состояния из Панель разработчика -> Состояния.

**Comment by Losenmann** [comment]
Прошу прощения за долгий ответ.
Ниже перечислены все доступные атрибуты и состояние:
![Снимок экрана от 2023-12-15 21-34-58](https://github.com/dext0r/yandex_smart_home/assets/39598154/3a7c7cae-681b-483b-a484-1107f5550777)

**Comment by dext0r** [comment]
Автоматически подхватить такой объект нет возможности. Если хочется передавать в УДЯ состояние стиральной машины, то можно создать выключатель на шаблоне и передавать его, например:
```yaml
switch:
  - platform: template
    switches:
      washing_machine:
        value_template: '{{ is_state("sensor.stiralnaia_mashina", "on") }}'
        turn_on: {service: 'none.none'}
        turn_off: {service: 'none.none'}
```

Остальное атрибуты так же вряд ли получится сопоставить с умениями в УДЯ (нет ничего подходящего).
