### ISSUE TITLE
Switch не поддерживает current

### ISSUE THREAD

**Issue by Antonzlo** [dext0r/yandex_smart_home#517]
```yaml
switch.obogrevatel:
      name: Обогреватель
      properties:
        - type: voltage
          entity: sensor.napriazhenie_obogrevatel
        - type: power
          entity: sensor.moshchnost_obogrevatel
        - type: current
          entity: sensor.tok_obogrevatel
```
Выдает 
```
Invalid config for 'yandex_smart_home' at configuration.yaml, line 54: Property type 'current' is not supported. See valid types at https://yandex.ru/dev/dialogs/smart-home/doc/concepts/float-instance.html and https://yandex.ru/dev/dialogs/smart-home/doc/concepts/event-instance.html for dictionary value 'yandex_smart_home->entity_config->switch.obogrevatel->properties->2->type', got 'current'
```
Если убрать ток, напряжение и мощность отображаются корректно
