### ISSUE TITLE
Кондиционер TCL TAC-07CHSA/TPG-W

### ISSUE THREAD

**Issue by kai-zer-ru** [dext0r/yandex_smart_home#527]
Предлагаю свою версию конфигурации кондиционера TCL TAC-07CHSA/TPG-W, подключенную через интеграцию ESPHome с помощью статьи https://dzen.ru/a/Zg0IyqT3hzDFC_VE и автора компонента https://dzen.ru/solovey_with_payalnik

```
climate.tclac_tclac_climate:
      name: Кондиционер
      type: devices.types.thermostat.ac
      room: Зал
      properties:
# сторонний датчик температуры
        - type: temperature
          entity: sensor.0x00158d0000dacf06_temperature
# сторонний датчик влажности
        - type: humidity
          entity: sensor.0x00158d0000dacf06_humidity
      modes:
        thermostat:
          heat: ['heat']
          cool: ['cool']
          auto: ['auto']
          dry: ['dry']
          fan_only: ['fan_only']
        fan_speed:
          auto: ['auto']
          low: ['low']
          medium: ['medium']
          high: ['high']
          turbo: ['diffuse']
          quiet: ['quiet']
        swing:
          stationary: ['off']
          auto: ['both']
          vertical: ['vertical']
          horizontal: ['horizontal']
```
