### ISSUE TITLE
Не удаётся настроить интеграцию при прямом подключении

### ISSUE THREAD

**Issue by Xoma163** [dext0r/yandex_smart_home#529]
Привет.

Сделал по гайду [здесь](https://docs.yaha-cloud.ru/v0.6.x/advanced/direct-connection/#notifier)
Устройства добавить получилось, всё ок. 
Но когда пытаюсь добавить notifier, то интеграция помирает. Логов никаких не пишется, в режиме отладки тоже.

```
yandex_smart_home:
  notifier:
    - oauth_token: AQAAAAAT******
      skill_id: 60f6b3***
      user_id: person.andrei
```

Что я делаю не так? Как можно получить какие-то логи? 
Спасибо
