### ISSUE TITLE
SkyKettle RK-G200S статус и температуру прокидывает в УДЯ, но не даёт включать

### ISSUE THREAD

**Issue by Mihail-A** [dext0r/yandex_smart_home#548]
SkyKettle RK-G200S статус и температуру прокидывает в УДЯ, но не даёт включать
![Screenshot_2](https://github.com/user-attachments/assets/22ebd7b0-2dc0-4dc3-a851-73cae3635354)
сегодня такое началось, куда копать ?

**Comment by ops244** [comment]
подтверждаю, help!

**Comment by asporykhin** [comment]
Тоже отвалилось включение-выключение чайника (skykettle_rk_m216s) после апгрейда HA с 2024.7.4 на 2024.9.1.

Пока вылечилось явным указанием переключателя в свойствах чайника в конфиге для Yandex Smart Home:

![image](https://github.com/user-attachments/assets/7d7fda56-c3f3-4e0c-a526-2f027e228641)

**Comment by leyalate35** [comment]
> Тоже отвалилось включение-выключение чайника (skykettle_rk_m216s) после апгрейда HA с 2024.7.4 на 2024.9.1.
> 
> Пока вылечилось явным указанием переключателя в свойствах чайника в конфиге для Yandex Smart Home:
> 
> ![image](https://private-user-images.githubusercontent.com/7592772/366421006-7d7fda56-c3f3-4e0c-a526-2f027e228641.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNTI0ODgsIm5iZiI6MTcyNjA1MjE4OCwicGF0aCI6Ii83NTkyNzcyLzM2NjQyMTAwNi03ZDdmZGE1Ni1jM2YzLTRlMGMtYTUyNi0yZjAyN2UyMjg2NDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTFUMTA1NjI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDMxNjkyNDQxOWRhOTJiYWEwODk1ODU4OWU0NmQ0NTZjOWVjNTEzMzc0YTg5YjNhZGU3NDkxYjRiZjAzMDU2OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Irykb1wNon3ENvEUoJjLtPJ3yC63iWjdoV9_ILN5HYM)

будьте так добры, объясните безграмотным где и что поправить?

**Comment by asporykhin** [comment]
Добавьте в configuration.yaml параметры устройства для Yandex Smart Home, как описано тут:
https://docs.yaha-cloud.ru/v0.6.x/config/getting-started/#yaml

Можно сделать это в главном файле configuration.yaml либо вынести в отдельный файл (рекомендую).

У меня выглядит так:
в configuration.yaml добавлена строка:

yandex_smart_home: !include yandex_smart_home.yaml

и создан файл yandex_smart_home.yaml, в котором собрана конфигурация для Yandex Smart Home (см. документацию по ссылке выше)

мой конфиг для чайника (за основу взят пример из документации https://docs.yaha-cloud.ru/v0.6.x/recipes/#redmond-kettle-clusterm):

```
entity_config:
  water_heater.skykettle_rk_m216s:
    name: Чайник
    room: Кухня
    type: devices.types.cooking.kettle
    turn_on:
      service: switch.turn_on
      entity_id: switch.skykettle_rk_m216s
    turn_off:
      service: switch.turn_off
      entity_id: switch.skykettle_rk_m216s
    properties:
      - type: temperature
        entity: water_heater.skykettle_rk_m216s
        attribute: current_temperature
    custom_toggles:
      backlight:
        state_entity_id: switch.skykettle_rk_m216s_enable_sync_light
        turn_on:
          service: switch.turn_on
          entity_id: switch.skykettle_rk_m216s_enable_sync_light
        turn_off:
          service: switch.turn_off
          entity_id: switch.skykettle_rk_m216s_enable_sync_light
      mute:
        state_entity_id: switch.skykettle_rk_m216s_enable_sound
        turn_on:
          service: switch.turn_on
          entity_id: switch.skykettle_rk_m216s_enable_sound
        turn_off:
          service: switch.turn_off
          entity_id: switch.skykettle_rk_m216s_enable_sound
    custom_ranges:
      temperature:
        state_attribute: temperature
        set_value:
          service: water_heater.set_temperature
          data:
            temperature: '{{ value }}'
        range:
          min: 25
          max: 100
          precision: 5

```          
Разумеется, все идентификаторы подставляем свои, и, конечно, не все свойства поддерживаются всеми чайниками, так что придется подправить под свои нужды.

**Comment by KVAZARUSS** [comment]
В УДЯ закинул switch.skykettle_rk_g210s. Назвал так же - чайник. Сильно пока не напрягает. Сценарии не делал ещё. Всё же жду когда поправят.

**Comment by Mihail-A** [comment]
Товарищи, не смотря на то, что чайник не включается, оказывается, его можно включить командой:
"Алиса, нагрей чайник до ста градусов" )

**Comment by dext0r** [comment]
Должно исправиться в 0.6.15

**Comment by Mihail-A** [comment]
![Screenshot_3](https://github.com/user-attachments/assets/30edb861-4605-47fc-897f-3b30d012c0f0)

вроде как должно было бы заработать, но нет...  не работает.

**Comment by Mihail-A** [comment]
> Да, поторопился, убрал строчку о починке из чейджлога

когда заработает ? )

**Comment by dext0r** [comment]
[capability_onoff.py.zip](https://github.com/user-attachments/files/17605806/capability_onoff.py.zip)

Распакуйте архив, замените файлик в custom_components/yandex_smart_home, перезагрузите HA и проверьте включается ли.

**Comment by Danstiv** [comment]
Пару недель назад обновил всё подряд и тоже вылез этот баг, но при попытке вызова сервиса из dev tools получил такое.
Failed to perform the action water_heater.turn_off. Entity water_heater.kettle1 does not support this service.
Из чего сделал вывод, что это сломано на стороне sky kettle, и yandex smart home не причём, но руки не дошли разобраться до конца и открыть issue / пофиксить.
А workaround такой придумал
```
  entity_config:
    water_heater.kettle1:
      turn_on:
        action: water_heater.set_operation_mode
        target:
          entity_id: water_heater.kettle1
        data:
          operation_mode: "Boil"
      turn_off:
        action: water_heater.set_operation_mode
        target:
          entity_id: water_heater.kettle1
        data:
          operation_mode: "off"
```
